url: "http://www.spdk.io"
baseurl: ""
title: Storage Performance Development Kit
title-cn: Storage Performance Development Kit
email: benjamin.walker@intel.com
author: Benjamin Walker
description: >
  The Storage Performance Development Kit (SPDK) provides a set of tools and libraries
  for writing high performance, scalable, user-mode storage applications.
  It achieves high performance by moving all of the necessary drivers into userspace
  and operating in a polled mode instead of relying on interrupts,
  which avoids kernel context switches and eliminates interrupt handling overhead.
markdown: kramdown
highlighter: rouge
permalink: pretty
include: [.well-known]

boxes:
  - title: download
    title-cn: 下载
    url: /releases/
  - title: documentation
    title-cn: 文档
    url: /doc/
  - title: development
    title-cn: 开发
    url: /development/
  - title: CI status
    title-cn: 集成测试
    url: /ci/
  - title: community
    title-cn: 社区
    url: /community/
  - title: Blog
    title-cn: 博客
    url: /blog/
  - title: Roadmap
    title-cn: 路线图
    url: https://trello.com/b/MN8auadQ/spdk-roadmap
  - title: News
    title-cn: 动态
    url: /news/
