url: "http://www.spdk.io"
baseurl: ""
title: Storage Performance Development Kit
email: benjamin.walker@intel.com
author: Benjamin Walker
description: >
  The Storage Performance Development Kit (SPDK) provides a set of tools and libraries
  for writing high performance, scalable, user-mode storage applications.
  It achieves high performance by moving all of the necessary drivers into userspace
  and operating in a polled mode instead of relying on interrupts,
  which avoids kernel context switches and eliminates interrupt handling overhead.
markdown: kramdown
permalink: pretty

boxes:
  - title: home
    url: /
    ico: home
  - title: download
    url: /releases/
    ico: download-alt
  - title: documentation
    url: /doc/
    ico: book
  - title: development
    url: /development/
    ico: wrench
  - title: CI status
    url: https://ci.spdk.io/
    ico: ok
  - title: community
    url: /community/
    ico: envelope
  - title: Blog
    url: /blog/
    ico: comment
  - title: Roadmap
    url: https://github.com/spdk/spdk/wiki/Roadmap
    ico: map-marker
  - title: News
    url: https://github.com/spdk/spdk/wiki/News
    ico: bullhorn


gems:
  - jekyll-feed
