url: "https://spdk.github.io"
baseurl: ""
title: Storage Performance Development Kit
email: benjamin.walker@intel.com
author: Benjamin Walker
description: >
  The Storage Performance Development Kit (SPDK) provides a set of tools and libraries
  for writing high performance, scalable, user-mode storage applications.
  It achieves high performance by moving all of the necessary drivers into userspace
  and operating in a polled mode instead of relying on interrupts,
  which avoids kernel context switches and eliminates interrupt handling overhead.
copyright: 'Copyright &copy; Intel Corporation. All Rights Reserved.'
markdown: kramdown
permalink: pretty

boxes:
  - title: 01.org
    url: https://01.org/spdk
    ico: img/ico/01.png
  - title: github
    url: https://github.com/spdk/spdk
    ico: img/ico/github.png
